language: cpp
compiler: gcc
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - doxygen
      - graphviz

install:
  - export CC=gcc-7
  - export CXX=g++-7
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo env "PATH=$PATH" cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
  - doxygen Doxyfile

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T graph_editor-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uandrewgavluk:$BINTRAY_API_KEY "https://api.bintray.com/content/andrewgavluk/Otus-1/otus-4_graph_editor/$TRAVIS_BUILD_NUMBER/graph_editor-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
